ALTER TABLE tasks ADD COLUMN IF NOT EXISTS branch_condition JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_bundle_root BOOLEAN DEFAULT FALSE;

ALTER TABLE task_versions ADD COLUMN IF NOT EXISTS branch_condition JSONB;
ALTER TABLE task_versions ADD COLUMN IF NOT EXISTS is_bundle_root BOOLEAN DEFAULT FALSE;
