// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID
	UserID       pgtype.Text
	Action       string
	ResourceType string
	ResourceID   pgtype.Text
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

type DlqTask struct {
	ID           pgtype.UUID
	TaskID       pgtype.UUID
	ErrorMessage pgtype.Text
	FailedAt     pgtype.Timestamptz
}

type ExecutionTrace struct {
	ID           pgtype.UUID
	TaskID       pgtype.UUID
	ExecutionID  string
	WorkerID     string
	StepName     string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	DurationMs   pgtype.Int4
	InputData    []byte
	OutputData   []byte
	IsError      pgtype.Bool
	ErrorMessage pgtype.Text
}

type OutboundWebhook struct {
	ID                     pgtype.UUID
	UserID                 string
	EndpointUrl            string
	EventTypes             []byte
	EncryptedSigningSecret []byte
	IsActive               bool
	CreatedAt              pgtype.Timestamptz
}

type SeoSetting struct {
	ID          int32
	Title       string
	Description string
	Keywords    string
	OgImage     pgtype.Text
	UpdatedAt   pgtype.Timestamptz
}

type Task struct {
	ID                  pgtype.UUID
	UserID              string
	Name                string
	TriggerType         pgtype.Text
	TriggerConfig       []byte
	AgentPrompt         string
	Status              pgtype.Text
	LockedBy            pgtype.Text
	NextRun             pgtype.Timestamptz
	LastRun             pgtype.Timestamptz
	FailureCount        pgtype.Int4
	MissedTaskPolicy    pgtype.Text
	DependsOnTaskID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	RequiresApproval    pgtype.Bool
	EncryptedSecrets    []byte
	LastApprovalStatus  pgtype.Text
	TriggerOnCompletion pgtype.Bool
	TaskType            pgtype.Text
	NativeCode          pgtype.Text
	WorkspaceID         pgtype.UUID
	MaxRetries          pgtype.Int4
	RetryCount          pgtype.Int4
	BackoffStrategy     pgtype.Text
	UiCoordinates       []byte
}

type TaskLog struct {
	ID            pgtype.UUID
	TaskID        pgtype.UUID
	UserID        string
	ExecutionTime pgtype.Timestamptz
	Status        string
	LlmResponse   pgtype.Text
	ErrorMessage  pgtype.Text
}

type Template struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Config      []byte
	IsPublic    pgtype.Bool
	WorkspaceID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	PriceID     pgtype.Text
	IsPremium   pgtype.Bool
	AuthorID    pgtype.Text
}

type User struct {
	ID           string
	ApiKey       string
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Role         pgtype.Text
	LastLogin    pgtype.Timestamptz
	Tier         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserSecret struct {
	ID             pgtype.UUID
	UserID         string
	Name           string
	EncryptedValue []byte
	CreatedAt      pgtype.Timestamptz
}

type UserTemplateSubscription struct {
	UserID       string
	TemplateID   pgtype.UUID
	SubscribedAt pgtype.Timestamptz
}

type WebSession struct {
	ID        pgtype.UUID
	UserID    pgtype.Text
	ExpiresAt pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID           pgtype.UUID
	WebhookID    pgtype.UUID
	UserID       string
	EventType    string
	StatusCode   pgtype.Int4
	Success      bool
	ResponseBody pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WebhookTrigger struct {
	ID        pgtype.UUID
	TaskID    pgtype.UUID
	Token     string
	CreatedAt pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   string
	CreatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      string
	Role        pgtype.Text
}
