// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID                  pgtype.UUID
	UserID              string
	Name                string
	TriggerType         pgtype.Text
	TriggerConfig       []byte
	AgentPrompt         string
	Status              pgtype.Text
	LockedBy            pgtype.Text
	NextRun             pgtype.Timestamptz
	LastRun             pgtype.Timestamptz
	FailureCount        pgtype.Int4
	MissedTaskPolicy    pgtype.Text
	DependsOnTaskID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	RequiresApproval    pgtype.Bool
	EncryptedSecrets    []byte
	LastApprovalStatus  pgtype.Text
	TriggerOnCompletion pgtype.Bool
}

type TaskLog struct {
	ID            pgtype.UUID
	TaskID        pgtype.UUID
	UserID        string
	ExecutionTime pgtype.Timestamptz
	Status        string
	LlmResponse   pgtype.Text
	ErrorMessage  pgtype.Text
}

type User struct {
	ID           string
	ApiKey       string
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Role         pgtype.Text
	LastLogin    pgtype.Timestamptz
	Tier         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserSecret struct {
	ID             pgtype.UUID
	UserID         string
	Name           string
	EncryptedValue []byte
	CreatedAt      pgtype.Timestamptz
}

type WebSession struct {
	ID        pgtype.UUID
	UserID    pgtype.Text
	ExpiresAt pgtype.Timestamptz
}
