// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTaskOwnership = `-- name: CheckTaskOwnership :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1 AND user_id = $2)
`

type CheckTaskOwnershipParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) CheckTaskOwnership(ctx context.Context, arg CheckTaskOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTaskOwnership, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkWorkspaceAccess = `-- name: CheckWorkspaceAccess :one
SELECT EXISTS (
    SELECT 1 FROM workspaces w
    LEFT JOIN workspace_members wm ON w.id = wm.workspace_id
    WHERE w.id = $1 AND (w.owner_id = $2 OR wm.user_id = $2)
) AS has_access
`

type CheckWorkspaceAccessParams struct {
	ID      pgtype.UUID
	OwnerID string
}

func (q *Queries) CheckWorkspaceAccess(ctx context.Context, arg CheckWorkspaceAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkspaceAccess, arg.ID, arg.OwnerID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const claimDueTasks = `-- name: ClaimDueTasks :many
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM fn_claim_due_tasks($1, $2)
`

type ClaimDueTasksParams struct {
	BatchSize int32
	WorkerID  string
}

func (q *Queries) ClaimDueTasks(ctx context.Context, arg ClaimDueTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, claimDueTasks, arg.BatchSize, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeTask = `-- name: CompleteTask :exec
SELECT fn_complete_task($1, $2, $3)
`

type CompleteTaskParams struct {
	TaskID     pgtype.UUID
	NewNextRun pgtype.Timestamptz
	NewStatus  string
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.Exec(ctx, completeTask, arg.TaskID, arg.NewNextRun, arg.NewStatus)
	return err
}

const countUserTasks = `-- name: CountUserTasks :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1
`

func (q *Queries) CountUserTasks(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	UserID       pgtype.Text
	Action       string
	ResourceType string
	ResourceID   pgtype.Text
	Metadata     []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const createExecutionTrace = `-- name: CreateExecutionTrace :one
INSERT INTO execution_traces (task_id, execution_id, worker_id, step_name, input_data, output_data, is_error, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, execution_id, worker_id, step_name, start_time, end_time, duration_ms, input_data, output_data, is_error, error_message
`

type CreateExecutionTraceParams struct {
	TaskID       pgtype.UUID
	ExecutionID  string
	WorkerID     string
	StepName     string
	InputData    []byte
	OutputData   []byte
	IsError      pgtype.Bool
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateExecutionTrace(ctx context.Context, arg CreateExecutionTraceParams) (ExecutionTrace, error) {
	row := q.db.QueryRow(ctx, createExecutionTrace,
		arg.TaskID,
		arg.ExecutionID,
		arg.WorkerID,
		arg.StepName,
		arg.InputData,
		arg.OutputData,
		arg.IsError,
		arg.ErrorMessage,
	)
	var i ExecutionTrace
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.WorkerID,
		&i.StepName,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMs,
		&i.InputData,
		&i.OutputData,
		&i.IsError,
		&i.ErrorMessage,
	)
	return i, err
}

const createOutboundWebhook = `-- name: CreateOutboundWebhook :one
INSERT INTO outbound_webhooks (user_id, endpoint_url, event_types, encrypted_signing_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateOutboundWebhookParams struct {
	UserID                 string
	EndpointUrl            string
	EventTypes             []byte
	EncryptedSigningSecret []byte
}

type CreateOutboundWebhookRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOutboundWebhook(ctx context.Context, arg CreateOutboundWebhookParams) (CreateOutboundWebhookRow, error) {
	row := q.db.QueryRow(ctx, createOutboundWebhook,
		arg.UserID,
		arg.EndpointUrl,
		arg.EventTypes,
		arg.EncryptedSigningSecret,
	)
	var i CreateOutboundWebhookRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, name, trigger_type, trigger_config, agent_prompt, missed_task_policy, depends_on_task_id, next_run, requires_approval, encrypted_secrets, trigger_on_completion) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) 
RETURNING id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates
`

type CreateTaskParams struct {
	UserID              string
	Name                string
	TriggerType         pgtype.Text
	TriggerConfig       []byte
	AgentPrompt         string
	MissedTaskPolicy    pgtype.Text
	DependsOnTaskID     pgtype.UUID
	NextRun             pgtype.Timestamptz
	RequiresApproval    pgtype.Bool
	EncryptedSecrets    []byte
	TriggerOnCompletion pgtype.Bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.AgentPrompt,
		arg.MissedTaskPolicy,
		arg.DependsOnTaskID,
		arg.NextRun,
		arg.RequiresApproval,
		arg.EncryptedSecrets,
		arg.TriggerOnCompletion,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const createTaskLog = `-- name: CreateTaskLog :one
INSERT INTO task_logs (task_id, user_id, status, error_message, llm_response) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTaskLogParams struct {
	TaskID       pgtype.UUID
	UserID       string
	Status       string
	ErrorMessage pgtype.Text
	LlmResponse  pgtype.Text
}

func (q *Queries) CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskLog,
		arg.TaskID,
		arg.UserID,
		arg.Status,
		arg.ErrorMessage,
		arg.LlmResponse,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, description, config, is_public, workspace_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, description, config, is_public, workspace_id, created_at, price_id, is_premium, author_id
`

type CreateTemplateParams struct {
	Name        string
	Description pgtype.Text
	Config      []byte
	IsPublic    pgtype.Bool
	WorkspaceID pgtype.UUID
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsPublic,
		arg.WorkspaceID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, api_key) 
VALUES ($1, $2, $3) 
RETURNING id, email, api_key, role, tier, created_at
`

type CreateUserParams struct {
	Email        pgtype.Text
	PasswordHash pgtype.Text
	ApiKey       string
}

type CreateUserRow struct {
	ID        string
	Email     pgtype.Text
	ApiKey    string
	Role      pgtype.Text
	Tier      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.ApiKey)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKey,
		&i.Role,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const createWebSession = `-- name: CreateWebSession :one
INSERT INTO web_sessions (user_id, expires_at) 
VALUES ($1, $2) 
RETURNING id
`

type CreateWebSessionParams struct {
	UserID    pgtype.Text
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWebSession, arg.UserID, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (webhook_id, user_id, event_type, status_code, success, response_body)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookDeliveryParams struct {
	WebhookID    pgtype.UUID
	UserID       string
	EventType    string
	StatusCode   pgtype.Int4
	Success      bool
	ResponseBody pgtype.Text
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.UserID,
		arg.EventType,
		arg.StatusCode,
		arg.Success,
		arg.ResponseBody,
	)
	return err
}

const createWebhookTrigger = `-- name: CreateWebhookTrigger :one
INSERT INTO webhook_triggers (task_id, token) VALUES ($1, $2) RETURNING id, task_id, token, created_at
`

type CreateWebhookTriggerParams struct {
	TaskID pgtype.UUID
	Token  string
}

func (q *Queries) CreateWebhookTrigger(ctx context.Context, arg CreateWebhookTriggerParams) (WebhookTrigger, error) {
	row := q.db.QueryRow(ctx, createWebhookTrigger, arg.TaskID, arg.Token)
	var i WebhookTrigger
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, owner_id) VALUES ($1, $2) RETURNING id, name, owner_id, created_at
`

type CreateWorkspaceParams struct {
	Name    string
	OwnerID string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOutboundWebhook = `-- name: DeleteOutboundWebhook :exec
DELETE FROM outbound_webhooks WHERE id = $1 AND user_id = $2
`

type DeleteOutboundWebhookParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) DeleteOutboundWebhook(ctx context.Context, arg DeleteOutboundWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteOutboundWebhook, arg.ID, arg.UserID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const deleteUserSecret = `-- name: DeleteUserSecret :exec
DELETE FROM user_secrets WHERE user_id = $1 AND name = $2
`

type DeleteUserSecretParams struct {
	UserID string
	Name   string
}

func (q *Queries) DeleteUserSecret(ctx context.Context, arg DeleteUserSecretParams) error {
	_, err := q.db.Exec(ctx, deleteUserSecret, arg.UserID, arg.Name)
	return err
}

const deleteWebSession = `-- name: DeleteWebSession :exec
DELETE FROM web_sessions WHERE id = $1
`

func (q *Queries) DeleteWebSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebSession, id)
	return err
}

const exportUserTasks = `-- name: ExportUserTasks :many
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks WHERE user_id = $1
`

func (q *Queries) ExportUserTasks(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, exportUserTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthInfoByEmail = `-- name: GetAuthInfoByEmail :one
SELECT id, password_hash FROM users WHERE email = $1
`

type GetAuthInfoByEmailRow struct {
	ID           string
	PasswordHash pgtype.Text
}

func (q *Queries) GetAuthInfoByEmail(ctx context.Context, email pgtype.Text) (GetAuthInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthInfoByEmail, email)
	var i GetAuthInfoByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getDependentTasksToTrigger = `-- name: GetDependentTasksToTrigger :many
SELECT t.id, t.user_id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, t.status, t.locked_by, t.next_run, t.last_run, t.failure_count, t.missed_task_policy, t.depends_on_task_id, t.created_at, t.requires_approval, t.encrypted_secrets, t.last_approval_status, t.trigger_on_completion, t.task_type, t.native_code, t.workspace_id, t.max_retries, t.retry_count, t.backoff_strategy, t.ui_coordinates FROM tasks t
INNER JOIN tasks parent ON t.depends_on_task_id = parent.id
WHERE t.depends_on_task_id = $1 
  AND t.trigger_on_completion = TRUE 
  AND t.status = 'active'
  AND t.user_id = parent.user_id
`

func (q *Queries) GetDependentTasksToTrigger(ctx context.Context, dependsOnTaskID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getDependentTasksToTrigger, dependsOnTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispatchableTaskByID = `-- name: GetDispatchableTaskByID :one
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks
WHERE id = $1
  AND user_id = $2
  AND status = 'processing'
  AND locked_by = $3
`

type GetDispatchableTaskByIDParams struct {
	ID       pgtype.UUID
	UserID   string
	LockedBy pgtype.Text
}

func (q *Queries) GetDispatchableTaskByID(ctx context.Context, arg GetDispatchableTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getDispatchableTaskByID, arg.ID, arg.UserID, arg.LockedBy)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getLatestTaskLogResponse = `-- name: GetLatestTaskLogResponse :one
SELECT l.llm_response FROM task_logs l
INNER JOIN tasks t ON l.task_id = t.id
WHERE l.task_id = $1 AND t.user_id = $2
ORDER BY l.execution_time DESC 
LIMIT 1
`

type GetLatestTaskLogResponseParams struct {
	TaskID pgtype.UUID
	UserID string
}

func (q *Queries) GetLatestTaskLogResponse(ctx context.Context, arg GetLatestTaskLogResponseParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLatestTaskLogResponse, arg.TaskID, arg.UserID)
	var llm_response pgtype.Text
	err := row.Scan(&llm_response)
	return llm_response, err
}

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT id, title, description, keywords, og_image, updated_at FROM seo_settings WHERE id = 1
`

func (q *Queries) GetSEOSettings(ctx context.Context) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, getSEOSettings)
	var i SeoSetting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Keywords,
		&i.OgImage,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemUsageMetrics = `-- name: GetSystemUsageMetrics :one
SELECT 
    (SELECT COUNT(*) FROM users) as user_count,
    (SELECT COUNT(*) FROM tasks) as task_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'success') as success_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'failure') as failure_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'missed') as missed_count,
    (SELECT COUNT(*) FROM audit_logs) as audit_count
`

type GetSystemUsageMetricsRow struct {
	UserCount    int64
	TaskCount    int64
	SuccessCount int64
	FailureCount int64
	MissedCount  int64
	AuditCount   int64
}

func (q *Queries) GetSystemUsageMetrics(ctx context.Context) (GetSystemUsageMetricsRow, error) {
	row := q.db.QueryRow(ctx, getSystemUsageMetrics)
	var i GetSystemUsageMetricsRow
	err := row.Scan(
		&i.UserCount,
		&i.TaskCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.MissedCount,
		&i.AuditCount,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getTaskByWebhookToken = `-- name: GetTaskByWebhookToken :one
SELECT t.id, t.user_id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, t.status, t.locked_by, t.next_run, t.last_run, t.failure_count, t.missed_task_policy, t.depends_on_task_id, t.created_at, t.requires_approval, t.encrypted_secrets, t.last_approval_status, t.trigger_on_completion, t.task_type, t.native_code, t.workspace_id, t.max_retries, t.retry_count, t.backoff_strategy, t.ui_coordinates FROM tasks t JOIN webhook_triggers w ON t.id = w.task_id WHERE w.token = $1
`

func (q *Queries) GetTaskByWebhookToken(ctx context.Context, token string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByWebhookToken, token)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getTaskLogs = `-- name: GetTaskLogs :many
SELECT l.id, l.task_id, l.user_id, l.execution_time, l.status, l.llm_response, l.error_message, t.name as task_name, u.email as user_email
FROM task_logs l
JOIN tasks t ON l.task_id = t.id
JOIN users u ON l.user_id = u.id
ORDER BY l.execution_time DESC
LIMIT 100
`

type GetTaskLogsRow struct {
	ID            pgtype.UUID
	TaskID        pgtype.UUID
	UserID        string
	ExecutionTime pgtype.Timestamptz
	Status        string
	LlmResponse   pgtype.Text
	ErrorMessage  pgtype.Text
	TaskName      string
	UserEmail     pgtype.Text
}

func (q *Queries) GetTaskLogs(ctx context.Context) ([]GetTaskLogsRow, error) {
	rows, err := q.db.Query(ctx, getTaskLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskLogsRow
	for rows.Next() {
		var i GetTaskLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.ExecutionTime,
			&i.Status,
			&i.LlmResponse,
			&i.ErrorMessage,
			&i.TaskName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateWithSubscription = `-- name: GetTemplateWithSubscription :one
SELECT t.id, t.name, t.description, t.config, t.is_public, t.workspace_id, t.created_at, t.price_id, t.is_premium, t.author_id, s.subscribed_at IS NOT NULL as is_subscribed
FROM templates t
LEFT JOIN user_template_subscriptions s ON t.id = s.template_id AND s.user_id = $1
WHERE t.id = $2
`

type GetTemplateWithSubscriptionParams struct {
	UserID string
	ID     pgtype.UUID
}

type GetTemplateWithSubscriptionRow struct {
	ID           pgtype.UUID
	Name         string
	Description  pgtype.Text
	Config       []byte
	IsPublic     pgtype.Bool
	WorkspaceID  pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	PriceID      pgtype.Text
	IsPremium    pgtype.Bool
	AuthorID     pgtype.Text
	IsSubscribed interface{}
}

func (q *Queries) GetTemplateWithSubscription(ctx context.Context, arg GetTemplateWithSubscriptionParams) (GetTemplateWithSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getTemplateWithSubscription, arg.UserID, arg.ID)
	var i GetTemplateWithSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
		&i.IsSubscribed,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, tier FROM users WHERE api_key = $1
`

type GetUserByAPIKeyRow struct {
	ID   string
	Tier pgtype.Text
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey string) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i GetUserByAPIKeyRow
	err := row.Scan(&i.ID, &i.Tier)
	return i, err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT u.id, u.email, u.api_key, u.role, u.tier, u.created_at 
FROM web_sessions s 
JOIN users u ON s.user_id = u.id 
WHERE s.id = $1 AND s.expires_at > $2
`

type GetUserBySessionIDParams struct {
	ID        pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type GetUserBySessionIDRow struct {
	ID        string
	Email     pgtype.Text
	ApiKey    string
	Role      pgtype.Text
	Tier      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserBySessionID(ctx context.Context, arg GetUserBySessionIDParams) (GetUserBySessionIDRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionID, arg.ID, arg.ExpiresAt)
	var i GetUserBySessionIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKey,
		&i.Role,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email pgtype.Text
	err := row.Scan(&email)
	return email, err
}

const getUserSecret = `-- name: GetUserSecret :one
SELECT encrypted_value FROM user_secrets WHERE user_id = $1 AND name = $2
`

type GetUserSecretParams struct {
	UserID string
	Name   string
}

func (q *Queries) GetUserSecret(ctx context.Context, arg GetUserSecretParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserSecret, arg.UserID, arg.Name)
	var encrypted_value []byte
	err := row.Scan(&encrypted_value)
	return encrypted_value, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT w.id, w.name, w.owner_id, w.created_at FROM workspaces w 
LEFT JOIN workspace_members wm ON w.id = wm.workspace_id 
WHERE w.owner_id = $1 OR wm.user_id = $1
`

func (q *Queries) GetUserWorkspaces(ctx context.Context, ownerID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskFailureCount = `-- name: IncrementTaskFailureCount :one
UPDATE tasks SET failure_count = failure_count + 1 
WHERE id = $1 AND user_id = $2
RETURNING failure_count
`

type IncrementTaskFailureCountParams struct {
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) IncrementTaskFailureCount(ctx context.Context, arg IncrementTaskFailureCountParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, incrementTaskFailureCount, arg.ID, arg.UserID)
	var failure_count pgtype.Int4
	err := row.Scan(&failure_count)
	return failure_count, err
}

const linkTaskDependency = `-- name: LinkTaskDependency :exec
UPDATE tasks
SET depends_on_task_id = $1, trigger_on_completion = $2
WHERE id = $3 AND user_id = $4
`

type LinkTaskDependencyParams struct {
	DependsOnTaskID     pgtype.UUID
	TriggerOnCompletion pgtype.Bool
	ID                  pgtype.UUID
	UserID              string
}

func (q *Queries) LinkTaskDependency(ctx context.Context, arg LinkTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, linkTaskDependency,
		arg.DependsOnTaskID,
		arg.TriggerOnCompletion,
		arg.ID,
		arg.UserID,
	)
	return err
}

const listActiveOutboundWebhooks = `-- name: ListActiveOutboundWebhooks :many
SELECT id, endpoint_url, event_types, encrypted_signing_secret
FROM outbound_webhooks
WHERE user_id = $1 AND is_active = TRUE
`

type ListActiveOutboundWebhooksRow struct {
	ID                     pgtype.UUID
	EndpointUrl            string
	EventTypes             []byte
	EncryptedSigningSecret []byte
}

func (q *Queries) ListActiveOutboundWebhooks(ctx context.Context, userID string) ([]ListActiveOutboundWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listActiveOutboundWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOutboundWebhooksRow
	for rows.Next() {
		var i ListActiveOutboundWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointUrl,
			&i.EventTypes,
			&i.EncryptedSigningSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, metadata, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboundWebhooks = `-- name: ListOutboundWebhooks :many
SELECT id, endpoint_url, event_types, is_active, created_at
FROM outbound_webhooks
WHERE user_id = $1
`

type ListOutboundWebhooksRow struct {
	ID          pgtype.UUID
	EndpointUrl string
	EventTypes  []byte
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListOutboundWebhooks(ctx context.Context, userID string) ([]ListOutboundWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listOutboundWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboundWebhooksRow
	for rows.Next() {
		var i ListOutboundWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointUrl,
			&i.EventTypes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTraces = `-- name: ListTaskTraces :many
SELECT id, task_id, execution_id, worker_id, step_name, start_time, end_time, duration_ms, input_data, output_data, is_error, error_message FROM execution_traces WHERE task_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListTaskTraces(ctx context.Context, taskID pgtype.UUID) ([]ExecutionTrace, error) {
	rows, err := q.db.Query(ctx, listTaskTraces, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionTrace
	for rows.Next() {
		var i ExecutionTrace
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ExecutionID,
			&i.WorkerID,
			&i.StepName,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMs,
			&i.InputData,
			&i.OutputData,
			&i.IsError,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSecrets = `-- name: ListUserSecrets :many
SELECT id, name, created_at FROM user_secrets WHERE user_id = $1 ORDER BY name ASC
`

type ListUserSecretsRow struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUserSecrets(ctx context.Context, userID string) ([]ListUserSecretsRow, error) {
	rows, err := q.db.Query(ctx, listUserSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSecretsRow
	for rows.Next() {
		var i ListUserSecretsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTasks = `-- name: ListUserTasks :many
SELECT id, name, trigger_type, status, next_run, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion FROM tasks WHERE user_id = $1
`

type ListUserTasksRow struct {
	ID                  pgtype.UUID
	Name                string
	TriggerType         pgtype.Text
	Status              pgtype.Text
	NextRun             pgtype.Timestamptz
	RequiresApproval    pgtype.Bool
	EncryptedSecrets    []byte
	LastApprovalStatus  pgtype.Text
	TriggerOnCompletion pgtype.Bool
}

func (q *Queries) ListUserTasks(ctx context.Context, userID string) ([]ListUserTasksRow, error) {
	rows, err := q.db.Query(ctx, listUserTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTasksRow
	for rows.Next() {
		var i ListUserTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Status,
			&i.NextRun,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, api_key, role, tier, created_at FROM users ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        string
	Email     pgtype.Text
	ApiKey    string
	Role      pgtype.Text
	Tier      pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ApiKey,
			&i.Role,
			&i.Tier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, user_id, event_type, status_code, success, response_body, created_at FROM webhook_deliveries WHERE webhook_id = $1 AND user_id = $2 ORDER BY created_at DESC LIMIT 50
`

type ListWebhookDeliveriesParams struct {
	WebhookID pgtype.UUID
	UserID    string
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.UserID,
			&i.EventType,
			&i.StatusCode,
			&i.Success,
			&i.ResponseBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveToDLQ = `-- name: MoveToDLQ :one
INSERT INTO dlq_tasks (task_id, error_message) VALUES ($1, $2) RETURNING id, task_id, error_message, failed_at
`

type MoveToDLQParams struct {
	TaskID       pgtype.UUID
	ErrorMessage pgtype.Text
}

func (q *Queries) MoveToDLQ(ctx context.Context, arg MoveToDLQParams) (DlqTask, error) {
	row := q.db.QueryRow(ctx, moveToDLQ, arg.TaskID, arg.ErrorMessage)
	var i DlqTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ErrorMessage,
		&i.FailedAt,
	)
	return i, err
}

const reapStuckTasks = `-- name: ReapStuckTasks :execrows
UPDATE tasks 
SET status = 'active', locked_by = NULL 
WHERE status = 'processing' AND next_run < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) ReapStuckTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapStuckTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskFailureCount = `-- name: ResetTaskFailureCount :exec
UPDATE tasks SET status = $1, failure_count = 0 WHERE id = $2 AND user_id = $3
`

type ResetTaskFailureCountParams struct {
	Status pgtype.Text
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) ResetTaskFailureCount(ctx context.Context, arg ResetTaskFailureCountParams) error {
	_, err := q.db.Exec(ctx, resetTaskFailureCount, arg.Status, arg.ID, arg.UserID)
	return err
}

const revertProcessingTasks = `-- name: RevertProcessingTasks :exec
UPDATE tasks SET status = 'active', locked_by = NULL WHERE locked_by = $1
`

func (q *Queries) RevertProcessingTasks(ctx context.Context, lockedBy pgtype.Text) error {
	_, err := q.db.Exec(ctx, revertProcessingTasks, lockedBy)
	return err
}

const setUserRoleByEmail = `-- name: SetUserRoleByEmail :exec
UPDATE users SET role = $1 WHERE email = $2
`

type SetUserRoleByEmailParams struct {
	Role  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) SetUserRoleByEmail(ctx context.Context, arg SetUserRoleByEmailParams) error {
	_, err := q.db.Exec(ctx, setUserRoleByEmail, arg.Role, arg.Email)
	return err
}

const updateSEOSettings = `-- name: UpdateSEOSettings :exec
UPDATE seo_settings 
SET title = $1, description = $2, keywords = $3, og_image = $4, updated_at = NOW()
WHERE id = 1
`

type UpdateSEOSettingsParams struct {
	Title       string
	Description string
	Keywords    string
	OgImage     pgtype.Text
}

func (q *Queries) UpdateSEOSettings(ctx context.Context, arg UpdateSEOSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSEOSettings,
		arg.Title,
		arg.Description,
		arg.Keywords,
		arg.OgImage,
	)
	return err
}

const updateTaskAgentPromptAndPolicy = `-- name: UpdateTaskAgentPromptAndPolicy :exec
UPDATE tasks
SET agent_prompt = $1, missed_task_policy = $2
WHERE id = $3 AND user_id = $4
`

type UpdateTaskAgentPromptAndPolicyParams struct {
	AgentPrompt      string
	MissedTaskPolicy pgtype.Text
	ID               pgtype.UUID
	UserID           string
}

func (q *Queries) UpdateTaskAgentPromptAndPolicy(ctx context.Context, arg UpdateTaskAgentPromptAndPolicyParams) error {
	_, err := q.db.Exec(ctx, updateTaskAgentPromptAndPolicy,
		arg.AgentPrompt,
		arg.MissedTaskPolicy,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTaskApprovalStatus = `-- name: UpdateTaskApprovalStatus :exec
UPDATE tasks SET last_approval_status = $1, status = $2, locked_by = NULL WHERE id = $3 AND user_id = $4
`

type UpdateTaskApprovalStatusParams struct {
	LastApprovalStatus pgtype.Text
	Status             pgtype.Text
	ID                 pgtype.UUID
	UserID             string
}

func (q *Queries) UpdateTaskApprovalStatus(ctx context.Context, arg UpdateTaskApprovalStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskApprovalStatus,
		arg.LastApprovalStatus,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTaskNextRun = `-- name: UpdateTaskNextRun :exec
UPDATE tasks SET status = $1, locked_by = NULL, next_run = $2 WHERE id = $3
`

type UpdateTaskNextRunParams struct {
	Status  pgtype.Text
	NextRun pgtype.Timestamptz
	ID      pgtype.UUID
}

func (q *Queries) UpdateTaskNextRun(ctx context.Context, arg UpdateTaskNextRunParams) error {
	_, err := q.db.Exec(ctx, updateTaskNextRun, arg.Status, arg.NextRun, arg.ID)
	return err
}

const updateTaskRetryCount = `-- name: UpdateTaskRetryCount :exec
UPDATE tasks SET retry_count = $1 WHERE id = $2 AND user_id = $3
`

type UpdateTaskRetryCountParams struct {
	RetryCount pgtype.Int4
	ID         pgtype.UUID
	UserID     string
}

func (q *Queries) UpdateTaskRetryCount(ctx context.Context, arg UpdateTaskRetryCountParams) error {
	_, err := q.db.Exec(ctx, updateTaskRetryCount, arg.RetryCount, arg.ID, arg.UserID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $1, locked_by = NULL WHERE id = $2 AND user_id = $3
`

type UpdateTaskStatusParams struct {
	Status pgtype.Text
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateTaskStatusAndFailureCount = `-- name: UpdateTaskStatusAndFailureCount :exec
UPDATE tasks SET status = $1, locked_by = NULL, failure_count = $2, retry_count = $3 WHERE id = $4 AND user_id = $5
`

type UpdateTaskStatusAndFailureCountParams struct {
	Status       pgtype.Text
	FailureCount pgtype.Int4
	RetryCount   pgtype.Int4
	ID           pgtype.UUID
	UserID       string
}

func (q *Queries) UpdateTaskStatusAndFailureCount(ctx context.Context, arg UpdateTaskStatusAndFailureCountParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatusAndFailureCount,
		arg.Status,
		arg.FailureCount,
		arg.RetryCount,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTaskStatusByUserID = `-- name: UpdateTaskStatusByUserID :exec
UPDATE tasks SET status = $1, locked_by = NULL WHERE id = $2 AND user_id = $3
`

type UpdateTaskStatusByUserIDParams struct {
	Status pgtype.Text
	ID     pgtype.UUID
	UserID string
}

func (q *Queries) UpdateTaskStatusByUserID(ctx context.Context, arg UpdateTaskStatusByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatusByUserID, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateUserAPIKey = `-- name: UpdateUserAPIKey :exec
UPDATE users SET api_key = $1 WHERE id = $2
`

type UpdateUserAPIKeyParams struct {
	ApiKey string
	ID     string
}

func (q *Queries) UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateUserAPIKey, arg.ApiKey, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $1 WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role pgtype.Text
	ID   string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserTier = `-- name: UpdateUserTier :exec
UPDATE users SET tier = $1 WHERE id = $2
`

type UpdateUserTierParams struct {
	Tier pgtype.Text
	ID   string
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) error {
	_, err := q.db.Exec(ctx, updateUserTier, arg.Tier, arg.ID)
	return err
}

const upsertUserSecret = `-- name: UpsertUserSecret :one
INSERT INTO user_secrets (user_id, name, encrypted_value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, name) DO UPDATE SET encrypted_value = $3
RETURNING id
`

type UpsertUserSecretParams struct {
	UserID         string
	Name           string
	EncryptedValue []byte
}

func (q *Queries) UpsertUserSecret(ctx context.Context, arg UpsertUserSecretParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUserSecret, arg.UserID, arg.Name, arg.EncryptedValue)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
