// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries-templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementTemplateUses = `-- name: IncrementTemplateUses :one
UPDATE templates SET uses_count = uses_count + 1 WHERE id = $1 RETURNING uses_count
`

func (q *Queries) IncrementTemplateUses(ctx context.Context, id pgtype.UUID) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, incrementTemplateUses, id)
	var uses_count pgtype.Int4
	err := row.Scan(&uses_count)
	return uses_count, err
}
