// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTaskOwnership = `-- name: CheckTaskOwnership :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1 AND user_id = $2)
`

type CheckTaskOwnershipParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) CheckTaskOwnership(ctx context.Context, arg CheckTaskOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTaskOwnership, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkWorkspaceAccess = `-- name: CheckWorkspaceAccess :one
SELECT EXISTS (
    SELECT 1 FROM workspaces w
    LEFT JOIN workspace_members wm ON w.id = wm.workspace_id
    WHERE w.id = $1 AND (w.owner_id = $2 OR wm.user_id = $2)
) AS has_access
`

type CheckWorkspaceAccessParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) CheckWorkspaceAccess(ctx context.Context, arg CheckWorkspaceAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkWorkspaceAccess, arg.ID, arg.OwnerID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const claimDueTasks = `-- name: ClaimDueTasks :many
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM fn_claim_due_tasks($1, $2)
`

type ClaimDueTasksParams struct {
	BatchSize int32  `json:"batch_size"`
	WorkerID  string `json:"worker_id"`
}

func (q *Queries) ClaimDueTasks(ctx context.Context, arg ClaimDueTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, claimDueTasks, arg.BatchSize, arg.WorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeTask = `-- name: CompleteTask :exec
SELECT fn_complete_task($1, $2, $3)
`

type CompleteTaskParams struct {
	TaskID     pgtype.UUID        `json:"task_id"`
	NewNextRun pgtype.Timestamptz `json:"new_next_run"`
	NewStatus  string             `json:"new_status"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.Exec(ctx, completeTask, arg.TaskID, arg.NewNextRun, arg.NewStatus)
	return err
}

const countUserTasks = `-- name: CountUserTasks :one
SELECT COUNT(*) FROM tasks WHERE user_id = $1
`

func (q *Queries) CountUserTasks(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (user_id, action, resource_type, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	UserID       pgtype.Text `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const createExecutionTrace = `-- name: CreateExecutionTrace :one
INSERT INTO execution_traces (task_id, execution_id, worker_id, step_name, input_data, output_data, is_error, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, execution_id, worker_id, step_name, start_time, end_time, duration_ms, input_data, output_data, is_error, error_message
`

type CreateExecutionTraceParams struct {
	TaskID       pgtype.UUID `json:"task_id"`
	ExecutionID  string      `json:"execution_id"`
	WorkerID     string      `json:"worker_id"`
	StepName     string      `json:"step_name"`
	InputData    []byte      `json:"input_data"`
	OutputData   []byte      `json:"output_data"`
	IsError      pgtype.Bool `json:"is_error"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateExecutionTrace(ctx context.Context, arg CreateExecutionTraceParams) (ExecutionTrace, error) {
	row := q.db.QueryRow(ctx, createExecutionTrace,
		arg.TaskID,
		arg.ExecutionID,
		arg.WorkerID,
		arg.StepName,
		arg.InputData,
		arg.OutputData,
		arg.IsError,
		arg.ErrorMessage,
	)
	var i ExecutionTrace
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.WorkerID,
		&i.StepName,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMs,
		&i.InputData,
		&i.OutputData,
		&i.IsError,
		&i.ErrorMessage,
	)
	return i, err
}

const createOutboundWebhook = `-- name: CreateOutboundWebhook :one
INSERT INTO outbound_webhooks (user_id, endpoint_url, event_types, encrypted_signing_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateOutboundWebhookParams struct {
	UserID                 string `json:"user_id"`
	EndpointUrl            string `json:"endpoint_url"`
	EventTypes             []byte `json:"event_types"`
	EncryptedSigningSecret []byte `json:"encrypted_signing_secret"`
}

type CreateOutboundWebhookRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOutboundWebhook(ctx context.Context, arg CreateOutboundWebhookParams) (CreateOutboundWebhookRow, error) {
	row := q.db.QueryRow(ctx, createOutboundWebhook,
		arg.UserID,
		arg.EndpointUrl,
		arg.EventTypes,
		arg.EncryptedSigningSecret,
	)
	var i CreateOutboundWebhookRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, name, trigger_type, trigger_config, agent_prompt, missed_task_policy, depends_on_task_id, next_run, requires_approval, encrypted_secrets, trigger_on_completion, workspace_id, task_type, native_code) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) 
RETURNING id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates
`

type CreateTaskParams struct {
	UserID              string             `json:"user_id"`
	Name                string             `json:"name"`
	TriggerType         pgtype.Text        `json:"trigger_type"`
	TriggerConfig       []byte             `json:"trigger_config"`
	AgentPrompt         string             `json:"agent_prompt"`
	MissedTaskPolicy    pgtype.Text        `json:"missed_task_policy"`
	DependsOnTaskID     pgtype.UUID        `json:"depends_on_task_id"`
	NextRun             pgtype.Timestamptz `json:"next_run"`
	RequiresApproval    pgtype.Bool        `json:"requires_approval"`
	EncryptedSecrets    []byte             `json:"encrypted_secrets"`
	TriggerOnCompletion pgtype.Bool        `json:"trigger_on_completion"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	TaskType            pgtype.Text        `json:"task_type"`
	NativeCode          pgtype.Text        `json:"native_code"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.AgentPrompt,
		arg.MissedTaskPolicy,
		arg.DependsOnTaskID,
		arg.NextRun,
		arg.RequiresApproval,
		arg.EncryptedSecrets,
		arg.TriggerOnCompletion,
		arg.WorkspaceID,
		arg.TaskType,
		arg.NativeCode,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const createTaskLog = `-- name: CreateTaskLog :one
INSERT INTO task_logs (task_id, user_id, status, error_message, llm_response) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTaskLogParams struct {
	TaskID       pgtype.UUID `json:"task_id"`
	UserID       string      `json:"user_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	LlmResponse  pgtype.Text `json:"llm_response"`
}

func (q *Queries) CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskLog,
		arg.TaskID,
		arg.UserID,
		arg.Status,
		arg.ErrorMessage,
		arg.LlmResponse,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTaskVersion = `-- name: CreateTaskVersion :one
INSERT INTO task_versions (
    task_id, name, trigger_type, trigger_config, agent_prompt, 
    missed_task_policy, depends_on_task_id, requires_approval, 
    trigger_on_completion, task_type, native_code
) 
SELECT 
    t.id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, 
    t.missed_task_policy, t.depends_on_task_id, t.requires_approval, 
    t.trigger_on_completion, t.task_type, t.native_code
FROM tasks t WHERE t.id = $1 AND t.user_id = $2
RETURNING id, task_id, name, trigger_type, trigger_config, agent_prompt, missed_task_policy, depends_on_task_id, requires_approval, trigger_on_completion, task_type, native_code, created_at
`

type CreateTaskVersionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) CreateTaskVersion(ctx context.Context, arg CreateTaskVersionParams) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, createTaskVersion, arg.ID, arg.UserID)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.RequiresApproval,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, description, config, is_public, workspace_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, description, config, is_public, workspace_id, created_at, price_id, is_premium, author_id, uses_count
`

type CreateTemplateParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	IsPublic    pgtype.Bool `json:"is_public"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsPublic,
		arg.WorkspaceID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
		&i.UsesCount,
	)
	return i, err
}

const createTemplateSubscription = `-- name: CreateTemplateSubscription :exec
INSERT INTO user_template_subscriptions (user_id, template_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateTemplateSubscriptionParams struct {
	UserID     string      `json:"user_id"`
	TemplateID pgtype.UUID `json:"template_id"`
}

func (q *Queries) CreateTemplateSubscription(ctx context.Context, arg CreateTemplateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createTemplateSubscription, arg.UserID, arg.TemplateID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, api_key) 
VALUES ($1, $2, $3) 
RETURNING id, email, api_key, role, tier, created_at
`

type CreateUserParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	ApiKey       string      `json:"api_key"`
}

type CreateUserRow struct {
	ID        string             `json:"id"`
	Email     pgtype.Text        `json:"email"`
	ApiKey    string             `json:"api_key"`
	Role      pgtype.Text        `json:"role"`
	Tier      pgtype.Text        `json:"tier"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.ApiKey)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKey,
		&i.Role,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const createWebSession = `-- name: CreateWebSession :one
INSERT INTO web_sessions (user_id, expires_at) 
VALUES ($1, $2) 
RETURNING id
`

type CreateWebSessionParams struct {
	UserID    pgtype.Text        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWebSession, arg.UserID, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (webhook_id, user_id, event_type, status_code, success, response_body)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookDeliveryParams struct {
	WebhookID    pgtype.UUID `json:"webhook_id"`
	UserID       string      `json:"user_id"`
	EventType    string      `json:"event_type"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	Success      bool        `json:"success"`
	ResponseBody pgtype.Text `json:"response_body"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.UserID,
		arg.EventType,
		arg.StatusCode,
		arg.Success,
		arg.ResponseBody,
	)
	return err
}

const createWebhookTrigger = `-- name: CreateWebhookTrigger :one
INSERT INTO webhook_triggers (task_id, token) VALUES ($1, $2) RETURNING id, task_id, token, created_at
`

type CreateWebhookTriggerParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Token  string      `json:"token"`
}

func (q *Queries) CreateWebhookTrigger(ctx context.Context, arg CreateWebhookTriggerParams) (WebhookTrigger, error) {
	row := q.db.QueryRow(ctx, createWebhookTrigger, arg.TaskID, arg.Token)
	var i WebhookTrigger
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, owner_id) VALUES ($1, $2) RETURNING id, name, owner_id, created_at
`

type CreateWorkspaceParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOutboundWebhook = `-- name: DeleteOutboundWebhook :exec
DELETE FROM outbound_webhooks WHERE id = $1 AND user_id = $2
`

type DeleteOutboundWebhookParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteOutboundWebhook(ctx context.Context, arg DeleteOutboundWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteOutboundWebhook, arg.ID, arg.UserID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const deleteUserSecret = `-- name: DeleteUserSecret :exec
DELETE FROM user_secrets WHERE user_id = $1 AND name = $2
`

type DeleteUserSecretParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteUserSecret(ctx context.Context, arg DeleteUserSecretParams) error {
	_, err := q.db.Exec(ctx, deleteUserSecret, arg.UserID, arg.Name)
	return err
}

const deleteWebSession = `-- name: DeleteWebSession :exec
DELETE FROM web_sessions WHERE id = $1
`

func (q *Queries) DeleteWebSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebSession, id)
	return err
}

const deleteWorkspaceEnvVar = `-- name: DeleteWorkspaceEnvVar :exec
DELETE FROM workspace_env_vars WHERE workspace_id = $1 AND name = $2
`

type DeleteWorkspaceEnvVarParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) DeleteWorkspaceEnvVar(ctx context.Context, arg DeleteWorkspaceEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceEnvVar, arg.WorkspaceID, arg.Name)
	return err
}

const exportUserTasks = `-- name: ExportUserTasks :many
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks WHERE user_id = $1
`

func (q *Queries) ExportUserTasks(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, exportUserTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveWorkerCount = `-- name: GetActiveWorkerCount :one
SELECT COUNT(*) FROM worker_heartbeats WHERE last_heartbeat > NOW() - INTERVAL '2 minutes'
`

func (q *Queries) GetActiveWorkerCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveWorkerCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuthInfoByEmail = `-- name: GetAuthInfoByEmail :one
SELECT id, password_hash FROM users WHERE email = $1
`

type GetAuthInfoByEmailRow struct {
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) GetAuthInfoByEmail(ctx context.Context, email pgtype.Text) (GetAuthInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAuthInfoByEmail, email)
	var i GetAuthInfoByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getDailyExecutionTrends = `-- name: GetDailyExecutionTrends :many
SELECT 
    DATE(start_time)::text as date,
    COUNT(*)::int as count
FROM execution_traces
WHERE start_time > NOW() - INTERVAL '7 days'
GROUP BY DATE(start_time)
ORDER BY date ASC
`

type GetDailyExecutionTrendsRow struct {
	Date  string `json:"date"`
	Count int32  `json:"count"`
}

func (q *Queries) GetDailyExecutionTrends(ctx context.Context) ([]GetDailyExecutionTrendsRow, error) {
	rows, err := q.db.Query(ctx, getDailyExecutionTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyExecutionTrendsRow
	for rows.Next() {
		var i GetDailyExecutionTrendsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependentTasksToTrigger = `-- name: GetDependentTasksToTrigger :many
SELECT t.id, t.user_id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, t.status, t.locked_by, t.next_run, t.last_run, t.failure_count, t.missed_task_policy, t.depends_on_task_id, t.created_at, t.requires_approval, t.encrypted_secrets, t.last_approval_status, t.trigger_on_completion, t.task_type, t.native_code, t.workspace_id, t.max_retries, t.retry_count, t.backoff_strategy, t.ui_coordinates FROM tasks t
INNER JOIN tasks parent ON t.depends_on_task_id = parent.id
WHERE t.depends_on_task_id = $1 
  AND t.trigger_on_completion = TRUE 
  AND t.status = 'active'
  AND t.user_id = parent.user_id
`

func (q *Queries) GetDependentTasksToTrigger(ctx context.Context, dependsOnTaskID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getDependentTasksToTrigger, dependsOnTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispatchableTaskByID = `-- name: GetDispatchableTaskByID :one
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks
WHERE id = $1
  AND user_id = $2
  AND status = 'processing'
  AND locked_by = $3
`

type GetDispatchableTaskByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   string      `json:"user_id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) GetDispatchableTaskByID(ctx context.Context, arg GetDispatchableTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getDispatchableTaskByID, arg.ID, arg.UserID, arg.LockedBy)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getGlobalSuccessRate = `-- name: GetGlobalSuccessRate :one
SELECT 
    CASE 
        WHEN COUNT(*) = 0 THEN 100.0
        ELSE (COUNT(*) FILTER (WHERE is_error = FALSE)::float / COUNT(*)::float) * 100.0
    END as success_rate
FROM execution_traces
WHERE start_time > NOW() - INTERVAL '24 hours'
`

func (q *Queries) GetGlobalSuccessRate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getGlobalSuccessRate)
	var success_rate interface{}
	err := row.Scan(&success_rate)
	return success_rate, err
}

const getLatestTaskLogResponse = `-- name: GetLatestTaskLogResponse :one
SELECT l.llm_response FROM task_logs l
INNER JOIN tasks t ON l.task_id = t.id
WHERE l.task_id = $1 AND t.user_id = $2
ORDER BY l.execution_time DESC 
LIMIT 1
`

type GetLatestTaskLogResponseParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetLatestTaskLogResponse(ctx context.Context, arg GetLatestTaskLogResponseParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLatestTaskLogResponse, arg.TaskID, arg.UserID)
	var llm_response pgtype.Text
	err := row.Scan(&llm_response)
	return llm_response, err
}

const getP99ExecutionLatency = `-- name: GetP99ExecutionLatency :one
SELECT COALESCE(percentile_cont(0.99) WITHIN GROUP (ORDER BY duration_ms), 0)::float
FROM execution_traces
WHERE start_time > NOW() - INTERVAL '24 hours'
`

func (q *Queries) GetP99ExecutionLatency(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, getP99ExecutionLatency)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT id, title, description, keywords, og_image, updated_at FROM seo_settings WHERE id = 1
`

func (q *Queries) GetSEOSettings(ctx context.Context) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, getSEOSettings)
	var i SeoSetting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Keywords,
		&i.OgImage,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemUsageMetrics = `-- name: GetSystemUsageMetrics :one
SELECT 
    (SELECT COUNT(*) FROM users) as user_count,
    (SELECT COUNT(*) FROM tasks) as task_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'success') as success_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'failure') as failure_count,
    (SELECT COUNT(*) FROM task_logs WHERE status = 'missed') as missed_count,
    (SELECT COUNT(*) FROM audit_logs) as audit_count
`

type GetSystemUsageMetricsRow struct {
	UserCount    int64 `json:"user_count"`
	TaskCount    int64 `json:"task_count"`
	SuccessCount int64 `json:"success_count"`
	FailureCount int64 `json:"failure_count"`
	MissedCount  int64 `json:"missed_count"`
	AuditCount   int64 `json:"audit_count"`
}

func (q *Queries) GetSystemUsageMetrics(ctx context.Context) (GetSystemUsageMetricsRow, error) {
	row := q.db.QueryRow(ctx, getSystemUsageMetrics)
	var i GetSystemUsageMetricsRow
	err := row.Scan(
		&i.UserCount,
		&i.TaskCount,
		&i.SuccessCount,
		&i.FailureCount,
		&i.MissedCount,
		&i.AuditCount,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getTaskByWebhookToken = `-- name: GetTaskByWebhookToken :one
SELECT t.id, t.user_id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, t.status, t.locked_by, t.next_run, t.last_run, t.failure_count, t.missed_task_policy, t.depends_on_task_id, t.created_at, t.requires_approval, t.encrypted_secrets, t.last_approval_status, t.trigger_on_completion, t.task_type, t.native_code, t.workspace_id, t.max_retries, t.retry_count, t.backoff_strategy, t.ui_coordinates FROM tasks t JOIN webhook_triggers w ON t.id = w.task_id WHERE w.token = $1
`

func (q *Queries) GetTaskByWebhookToken(ctx context.Context, token string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByWebhookToken, token)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const getTaskLogs = `-- name: GetTaskLogs :many
SELECT l.id, l.task_id, l.user_id, l.execution_time, l.status, l.llm_response, l.error_message, t.name as task_name, u.email as user_email
FROM task_logs l
JOIN tasks t ON l.task_id = t.id
JOIN users u ON l.user_id = u.id
ORDER BY l.execution_time DESC
LIMIT 100
`

type GetTaskLogsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TaskID        pgtype.UUID        `json:"task_id"`
	UserID        string             `json:"user_id"`
	ExecutionTime pgtype.Timestamptz `json:"execution_time"`
	Status        string             `json:"status"`
	LlmResponse   pgtype.Text        `json:"llm_response"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	TaskName      string             `json:"task_name"`
	UserEmail     pgtype.Text        `json:"user_email"`
}

func (q *Queries) GetTaskLogs(ctx context.Context) ([]GetTaskLogsRow, error) {
	rows, err := q.db.Query(ctx, getTaskLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskLogsRow
	for rows.Next() {
		var i GetTaskLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.ExecutionTime,
			&i.Status,
			&i.LlmResponse,
			&i.ErrorMessage,
			&i.TaskName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskVersionByID = `-- name: GetTaskVersionByID :one
SELECT id, task_id, name, trigger_type, trigger_config, agent_prompt, missed_task_policy, depends_on_task_id, requires_approval, trigger_on_completion, task_type, native_code, created_at FROM task_versions WHERE id = $1 AND task_id = $2
`

type GetTaskVersionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) GetTaskVersionByID(ctx context.Context, arg GetTaskVersionByIDParams) (TaskVersion, error) {
	row := q.db.QueryRow(ctx, getTaskVersionByID, arg.ID, arg.TaskID)
	var i TaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.RequiresApproval,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskWorkspaceEnvVars = `-- name: GetTaskWorkspaceEnvVars :many
SELECT e.name, e.value 
FROM workspace_env_vars e
JOIN tasks t ON e.workspace_id = t.workspace_id
WHERE t.id = $1
`

type GetTaskWorkspaceEnvVarsRow struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (q *Queries) GetTaskWorkspaceEnvVars(ctx context.Context, id pgtype.UUID) ([]GetTaskWorkspaceEnvVarsRow, error) {
	rows, err := q.db.Query(ctx, getTaskWorkspaceEnvVars, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskWorkspaceEnvVarsRow
	for rows.Next() {
		var i GetTaskWorkspaceEnvVarsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateByIDRaw = `-- name: GetTemplateByIDRaw :one
SELECT id, name, description, config, is_public, workspace_id, created_at, price_id, is_premium, author_id, uses_count FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateByIDRaw(ctx context.Context, id pgtype.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByIDRaw, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
		&i.UsesCount,
	)
	return i, err
}

const getTemplateWithSubscription = `-- name: GetTemplateWithSubscription :one
SELECT t.id, t.name, t.description, t.config, t.is_public, t.workspace_id, t.created_at, t.price_id, t.is_premium, t.author_id, t.uses_count, s.subscribed_at IS NOT NULL as is_subscribed
FROM templates t
LEFT JOIN user_template_subscriptions s ON t.id = s.template_id AND s.user_id = $1
WHERE t.id = $2
`

type GetTemplateWithSubscriptionParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetTemplateWithSubscriptionRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Config       []byte             `json:"config"`
	IsPublic     pgtype.Bool        `json:"is_public"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PriceID      pgtype.Text        `json:"price_id"`
	IsPremium    pgtype.Bool        `json:"is_premium"`
	AuthorID     pgtype.Text        `json:"author_id"`
	UsesCount    pgtype.Int4        `json:"uses_count"`
	IsSubscribed interface{}        `json:"is_subscribed"`
}

func (q *Queries) GetTemplateWithSubscription(ctx context.Context, arg GetTemplateWithSubscriptionParams) (GetTemplateWithSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getTemplateWithSubscription, arg.UserID, arg.ID)
	var i GetTemplateWithSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
		&i.UsesCount,
		&i.IsSubscribed,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, api_key, role, tier, created_at FROM users WHERE id = $1
`

type GetUserRow struct {
	ID        string             `json:"id"`
	Email     pgtype.Text        `json:"email"`
	ApiKey    string             `json:"api_key"`
	Role      pgtype.Text        `json:"role"`
	Tier      pgtype.Text        `json:"tier"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKey,
		&i.Role,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, tier FROM users WHERE api_key = $1
`

type GetUserByAPIKeyRow struct {
	ID   string      `json:"id"`
	Tier pgtype.Text `json:"tier"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey string) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i GetUserByAPIKeyRow
	err := row.Scan(&i.ID, &i.Tier)
	return i, err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT u.id, u.email, u.api_key, u.role, u.tier, u.created_at 
FROM web_sessions s 
JOIN users u ON s.user_id = u.id 
WHERE s.id = $1 AND s.expires_at > $2
`

type GetUserBySessionIDParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type GetUserBySessionIDRow struct {
	ID        string             `json:"id"`
	Email     pgtype.Text        `json:"email"`
	ApiKey    string             `json:"api_key"`
	Role      pgtype.Text        `json:"role"`
	Tier      pgtype.Text        `json:"tier"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserBySessionID(ctx context.Context, arg GetUserBySessionIDParams) (GetUserBySessionIDRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionID, arg.ID, arg.ExpiresAt)
	var i GetUserBySessionIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ApiKey,
		&i.Role,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM users WHERE id = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email pgtype.Text
	err := row.Scan(&email)
	return email, err
}

const getUserSecret = `-- name: GetUserSecret :one
SELECT encrypted_value FROM user_secrets WHERE user_id = $1 AND name = $2
`

type GetUserSecretParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetUserSecret(ctx context.Context, arg GetUserSecretParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserSecret, arg.UserID, arg.Name)
	var encrypted_value []byte
	err := row.Scan(&encrypted_value)
	return encrypted_value, err
}

const getUserWorkspaces = `-- name: GetUserWorkspaces :many
SELECT w.id, w.name, w.owner_id, w.created_at FROM workspaces w 
LEFT JOIN workspace_members wm ON w.id = wm.workspace_id 
WHERE w.owner_id = $1 OR wm.user_id = $1
`

func (q *Queries) GetUserWorkspaces(ctx context.Context, ownerID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getUserWorkspaces, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskFailureCount = `-- name: IncrementTaskFailureCount :one
UPDATE tasks SET failure_count = failure_count + 1 
WHERE id = $1 AND user_id = $2
RETURNING failure_count
`

type IncrementTaskFailureCountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) IncrementTaskFailureCount(ctx context.Context, arg IncrementTaskFailureCountParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, incrementTaskFailureCount, arg.ID, arg.UserID)
	var failure_count pgtype.Int4
	err := row.Scan(&failure_count)
	return failure_count, err
}

const linkTaskDependency = `-- name: LinkTaskDependency :exec
UPDATE tasks
SET depends_on_task_id = $1, trigger_on_completion = $2
WHERE id = $3 AND user_id = $4
`

type LinkTaskDependencyParams struct {
	DependsOnTaskID     pgtype.UUID `json:"depends_on_task_id"`
	TriggerOnCompletion pgtype.Bool `json:"trigger_on_completion"`
	ID                  pgtype.UUID `json:"id"`
	UserID              string      `json:"user_id"`
}

func (q *Queries) LinkTaskDependency(ctx context.Context, arg LinkTaskDependencyParams) error {
	_, err := q.db.Exec(ctx, linkTaskDependency,
		arg.DependsOnTaskID,
		arg.TriggerOnCompletion,
		arg.ID,
		arg.UserID,
	)
	return err
}

const listActiveOutboundWebhooks = `-- name: ListActiveOutboundWebhooks :many
SELECT id, endpoint_url, event_types, encrypted_signing_secret
FROM outbound_webhooks
WHERE user_id = $1 AND is_active = TRUE
`

type ListActiveOutboundWebhooksRow struct {
	ID                     pgtype.UUID `json:"id"`
	EndpointUrl            string      `json:"endpoint_url"`
	EventTypes             []byte      `json:"event_types"`
	EncryptedSigningSecret []byte      `json:"encrypted_signing_secret"`
}

func (q *Queries) ListActiveOutboundWebhooks(ctx context.Context, userID string) ([]ListActiveOutboundWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listActiveOutboundWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOutboundWebhooksRow
	for rows.Next() {
		var i ListActiveOutboundWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointUrl,
			&i.EventTypes,
			&i.EncryptedSigningSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, metadata, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboundWebhooks = `-- name: ListOutboundWebhooks :many
SELECT id, endpoint_url, event_types, is_active, created_at
FROM outbound_webhooks
WHERE user_id = $1
`

type ListOutboundWebhooksRow struct {
	ID          pgtype.UUID        `json:"id"`
	EndpointUrl string             `json:"endpoint_url"`
	EventTypes  []byte             `json:"event_types"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOutboundWebhooks(ctx context.Context, userID string) ([]ListOutboundWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listOutboundWebhooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboundWebhooksRow
	for rows.Next() {
		var i ListOutboundWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointUrl,
			&i.EventTypes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTemplates = `-- name: ListPublicTemplates :many
SELECT id, name, description, config, is_public, workspace_id, created_at, price_id, is_premium, author_id, uses_count FROM templates 
WHERE is_public = true AND (name ILIKE $1 OR description ILIKE $1)
ORDER BY created_at DESC
`

func (q *Queries) ListPublicTemplates(ctx context.Context, name string) ([]Template, error) {
	rows, err := q.db.Query(ctx, listPublicTemplates, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.IsPublic,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.PriceID,
			&i.IsPremium,
			&i.AuthorID,
			&i.UsesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTraces = `-- name: ListTaskTraces :many
SELECT id, task_id, execution_id, worker_id, step_name, start_time, end_time, duration_ms, input_data, output_data, is_error, error_message FROM execution_traces WHERE task_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListTaskTraces(ctx context.Context, taskID pgtype.UUID) ([]ExecutionTrace, error) {
	rows, err := q.db.Query(ctx, listTaskTraces, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionTrace
	for rows.Next() {
		var i ExecutionTrace
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ExecutionID,
			&i.WorkerID,
			&i.StepName,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMs,
			&i.InputData,
			&i.OutputData,
			&i.IsError,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskVersions = `-- name: ListTaskVersions :many
SELECT id, task_id, name, trigger_type, trigger_config, agent_prompt, missed_task_policy, depends_on_task_id, requires_approval, trigger_on_completion, task_type, native_code, created_at FROM task_versions WHERE task_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTaskVersions(ctx context.Context, taskID pgtype.UUID) ([]TaskVersion, error) {
	rows, err := q.db.Query(ctx, listTaskVersions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskVersion
	for rows.Next() {
		var i TaskVersion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.RequiresApproval,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSecrets = `-- name: ListUserSecrets :many
SELECT id, name, created_at FROM user_secrets WHERE user_id = $1 ORDER BY name ASC
`

type ListUserSecretsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserSecrets(ctx context.Context, userID string) ([]ListUserSecretsRow, error) {
	rows, err := q.db.Query(ctx, listUserSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSecretsRow
	for rows.Next() {
		var i ListUserSecretsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTasks = `-- name: ListUserTasks :many
SELECT 
    t.id, t.user_id, t.name, t.trigger_type, t.trigger_config, t.agent_prompt, t.status, t.locked_by, t.next_run, t.last_run, t.failure_count, t.missed_task_policy, t.depends_on_task_id, t.created_at, t.requires_approval, t.encrypted_secrets, t.last_approval_status, t.trigger_on_completion, t.task_type, t.native_code, t.workspace_id, t.max_retries, t.retry_count, t.backoff_strategy, t.ui_coordinates,
    (SELECT COUNT(*) FROM task_versions tv WHERE tv.task_id = t.id) as version_count
FROM tasks t
WHERE t.user_id = $1
ORDER BY t.created_at DESC
`

type ListUserTasksRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              string             `json:"user_id"`
	Name                string             `json:"name"`
	TriggerType         pgtype.Text        `json:"trigger_type"`
	TriggerConfig       []byte             `json:"trigger_config"`
	AgentPrompt         string             `json:"agent_prompt"`
	Status              pgtype.Text        `json:"status"`
	LockedBy            pgtype.Text        `json:"locked_by"`
	NextRun             pgtype.Timestamptz `json:"next_run"`
	LastRun             pgtype.Timestamptz `json:"last_run"`
	FailureCount        pgtype.Int4        `json:"failure_count"`
	MissedTaskPolicy    pgtype.Text        `json:"missed_task_policy"`
	DependsOnTaskID     pgtype.UUID        `json:"depends_on_task_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	RequiresApproval    pgtype.Bool        `json:"requires_approval"`
	EncryptedSecrets    []byte             `json:"encrypted_secrets"`
	LastApprovalStatus  pgtype.Text        `json:"last_approval_status"`
	TriggerOnCompletion pgtype.Bool        `json:"trigger_on_completion"`
	TaskType            pgtype.Text        `json:"task_type"`
	NativeCode          pgtype.Text        `json:"native_code"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	MaxRetries          pgtype.Int4        `json:"max_retries"`
	RetryCount          pgtype.Int4        `json:"retry_count"`
	BackoffStrategy     pgtype.Text        `json:"backoff_strategy"`
	UiCoordinates       []byte             `json:"ui_coordinates"`
	VersionCount        int64              `json:"version_count"`
}

func (q *Queries) ListUserTasks(ctx context.Context, userID string) ([]ListUserTasksRow, error) {
	rows, err := q.db.Query(ctx, listUserTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTasksRow
	for rows.Next() {
		var i ListUserTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.AgentPrompt,
			&i.Status,
			&i.LockedBy,
			&i.NextRun,
			&i.LastRun,
			&i.FailureCount,
			&i.MissedTaskPolicy,
			&i.DependsOnTaskID,
			&i.CreatedAt,
			&i.RequiresApproval,
			&i.EncryptedSecrets,
			&i.LastApprovalStatus,
			&i.TriggerOnCompletion,
			&i.TaskType,
			&i.NativeCode,
			&i.WorkspaceID,
			&i.MaxRetries,
			&i.RetryCount,
			&i.BackoffStrategy,
			&i.UiCoordinates,
			&i.VersionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, api_key, role, tier, created_at 
FROM users 
WHERE email ILIKE $1 OR role ILIKE $1 OR tier ILIKE $1
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        string             `json:"id"`
	Email     pgtype.Text        `json:"email"`
	ApiKey    string             `json:"api_key"`
	Role      pgtype.Text        `json:"role"`
	Tier      pgtype.Text        `json:"tier"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, email pgtype.Text) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ApiKey,
			&i.Role,
			&i.Tier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, user_id, event_type, status_code, success, response_body, created_at FROM webhook_deliveries WHERE webhook_id = $1 AND user_id = $2 ORDER BY created_at DESC LIMIT 50
`

type ListWebhookDeliveriesParams struct {
	WebhookID pgtype.UUID `json:"webhook_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.UserID,
			&i.EventType,
			&i.StatusCode,
			&i.Success,
			&i.ResponseBody,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerHeartbeats = `-- name: ListWorkerHeartbeats :many
SELECT worker_id, hostname, last_heartbeat, task_count FROM worker_heartbeats ORDER BY last_heartbeat DESC
`

func (q *Queries) ListWorkerHeartbeats(ctx context.Context) ([]WorkerHeartbeat, error) {
	rows, err := q.db.Query(ctx, listWorkerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkerHeartbeat
	for rows.Next() {
		var i WorkerHeartbeat
		if err := rows.Scan(
			&i.WorkerID,
			&i.Hostname,
			&i.LastHeartbeat,
			&i.TaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceEnvVars = `-- name: ListWorkspaceEnvVars :many
SELECT id, workspace_id, name, value, created_at, updated_at FROM workspace_env_vars WHERE workspace_id = $1 ORDER BY name ASC
`

func (q *Queries) ListWorkspaceEnvVars(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceEnvVar, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEnvVars, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEnvVar
	for rows.Next() {
		var i WorkspaceEnvVar
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveToDLQ = `-- name: MoveToDLQ :one
INSERT INTO dlq_tasks (task_id, error_message) VALUES ($1, $2) RETURNING id, task_id, error_message, failed_at
`

type MoveToDLQParams struct {
	TaskID       pgtype.UUID `json:"task_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MoveToDLQ(ctx context.Context, arg MoveToDLQParams) (DlqTask, error) {
	row := q.db.QueryRow(ctx, moveToDLQ, arg.TaskID, arg.ErrorMessage)
	var i DlqTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ErrorMessage,
		&i.FailedAt,
	)
	return i, err
}

const reapStuckTasks = `-- name: ReapStuckTasks :execrows
UPDATE tasks 
SET status = 'active', locked_by = NULL 
WHERE status = 'processing' AND next_run < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) ReapStuckTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapStuckTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetTaskFailureCount = `-- name: ResetTaskFailureCount :exec
UPDATE tasks SET status = $1, failure_count = 0 WHERE id = $2 AND user_id = $3
`

type ResetTaskFailureCountParams struct {
	Status pgtype.Text `json:"status"`
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) ResetTaskFailureCount(ctx context.Context, arg ResetTaskFailureCountParams) error {
	_, err := q.db.Exec(ctx, resetTaskFailureCount, arg.Status, arg.ID, arg.UserID)
	return err
}

const restoreTaskFromVersion = `-- name: RestoreTaskFromVersion :exec
UPDATE tasks
SET 
    name = v.name,
    trigger_type = v.trigger_type,
    trigger_config = v.trigger_config,
    agent_prompt = v.agent_prompt,
    missed_task_policy = v.missed_task_policy,
    depends_on_task_id = v.depends_on_task_id,
    requires_approval = v.requires_approval,
    trigger_on_completion = v.trigger_on_completion,
    task_type = v.task_type,
    native_code = v.native_code
FROM task_versions v
WHERE tasks.id = $1 AND tasks.user_id = $2 AND v.id = $3 AND v.task_id = $1
`

type RestoreTaskFromVersionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
	ID_2   pgtype.UUID `json:"id_2"`
}

func (q *Queries) RestoreTaskFromVersion(ctx context.Context, arg RestoreTaskFromVersionParams) error {
	_, err := q.db.Exec(ctx, restoreTaskFromVersion, arg.ID, arg.UserID, arg.ID_2)
	return err
}

const revertProcessingTasks = `-- name: RevertProcessingTasks :exec
UPDATE tasks SET status = 'active', locked_by = NULL WHERE locked_by = $1
`

func (q *Queries) RevertProcessingTasks(ctx context.Context, lockedBy pgtype.Text) error {
	_, err := q.db.Exec(ctx, revertProcessingTasks, lockedBy)
	return err
}

const setUserRoleByEmail = `-- name: SetUserRoleByEmail :exec
UPDATE users SET role = $1 WHERE email = $2
`

type SetUserRoleByEmailParams struct {
	Role  pgtype.Text `json:"role"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) SetUserRoleByEmail(ctx context.Context, arg SetUserRoleByEmailParams) error {
	_, err := q.db.Exec(ctx, setUserRoleByEmail, arg.Role, arg.Email)
	return err
}

const updateSEOSettings = `-- name: UpdateSEOSettings :exec
UPDATE seo_settings 
SET title = $1, description = $2, keywords = $3, og_image = $4, updated_at = NOW()
WHERE id = 1
`

type UpdateSEOSettingsParams struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Keywords    string      `json:"keywords"`
	OgImage     pgtype.Text `json:"og_image"`
}

func (q *Queries) UpdateSEOSettings(ctx context.Context, arg UpdateSEOSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSEOSettings,
		arg.Title,
		arg.Description,
		arg.Keywords,
		arg.OgImage,
	)
	return err
}

const updateTaskAgentPromptAndPolicy = `-- name: UpdateTaskAgentPromptAndPolicy :one
UPDATE tasks
SET agent_prompt = $1, 
    missed_task_policy = $2,
    ui_coordinates = $3
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, name, trigger_type, trigger_config, agent_prompt, status, locked_by, next_run, last_run, failure_count, missed_task_policy, depends_on_task_id, created_at, requires_approval, encrypted_secrets, last_approval_status, trigger_on_completion, task_type, native_code, workspace_id, max_retries, retry_count, backoff_strategy, ui_coordinates
`

type UpdateTaskAgentPromptAndPolicyParams struct {
	AgentPrompt      string      `json:"agent_prompt"`
	MissedTaskPolicy pgtype.Text `json:"missed_task_policy"`
	UiCoordinates    []byte      `json:"ui_coordinates"`
	ID               pgtype.UUID `json:"id"`
	UserID           string      `json:"user_id"`
}

func (q *Queries) UpdateTaskAgentPromptAndPolicy(ctx context.Context, arg UpdateTaskAgentPromptAndPolicyParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAgentPromptAndPolicy,
		arg.AgentPrompt,
		arg.MissedTaskPolicy,
		arg.UiCoordinates,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.AgentPrompt,
		&i.Status,
		&i.LockedBy,
		&i.NextRun,
		&i.LastRun,
		&i.FailureCount,
		&i.MissedTaskPolicy,
		&i.DependsOnTaskID,
		&i.CreatedAt,
		&i.RequiresApproval,
		&i.EncryptedSecrets,
		&i.LastApprovalStatus,
		&i.TriggerOnCompletion,
		&i.TaskType,
		&i.NativeCode,
		&i.WorkspaceID,
		&i.MaxRetries,
		&i.RetryCount,
		&i.BackoffStrategy,
		&i.UiCoordinates,
	)
	return i, err
}

const updateTaskApprovalStatus = `-- name: UpdateTaskApprovalStatus :exec
UPDATE tasks SET last_approval_status = $1, status = $2, locked_by = NULL WHERE id = $3 AND user_id = $4
`

type UpdateTaskApprovalStatusParams struct {
	LastApprovalStatus pgtype.Text `json:"last_approval_status"`
	Status             pgtype.Text `json:"status"`
	ID                 pgtype.UUID `json:"id"`
	UserID             string      `json:"user_id"`
}

func (q *Queries) UpdateTaskApprovalStatus(ctx context.Context, arg UpdateTaskApprovalStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskApprovalStatus,
		arg.LastApprovalStatus,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTaskNextRun = `-- name: UpdateTaskNextRun :exec
UPDATE tasks SET status = $1, locked_by = NULL, next_run = $2 WHERE id = $3
`

type UpdateTaskNextRunParams struct {
	Status  pgtype.Text        `json:"status"`
	NextRun pgtype.Timestamptz `json:"next_run"`
	ID      pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTaskNextRun(ctx context.Context, arg UpdateTaskNextRunParams) error {
	_, err := q.db.Exec(ctx, updateTaskNextRun, arg.Status, arg.NextRun, arg.ID)
	return err
}

const updateTaskRetryCount = `-- name: UpdateTaskRetryCount :exec
UPDATE tasks SET retry_count = $1 WHERE id = $2 AND user_id = $3
`

type UpdateTaskRetryCountParams struct {
	RetryCount pgtype.Int4 `json:"retry_count"`
	ID         pgtype.UUID `json:"id"`
	UserID     string      `json:"user_id"`
}

func (q *Queries) UpdateTaskRetryCount(ctx context.Context, arg UpdateTaskRetryCountParams) error {
	_, err := q.db.Exec(ctx, updateTaskRetryCount, arg.RetryCount, arg.ID, arg.UserID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $1, locked_by = NULL WHERE id = $2 AND user_id = $3
`

type UpdateTaskStatusParams struct {
	Status pgtype.Text `json:"status"`
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateTaskStatusAndFailureCount = `-- name: UpdateTaskStatusAndFailureCount :exec
UPDATE tasks SET status = $1, locked_by = NULL, failure_count = $2, retry_count = $3 WHERE id = $4 AND user_id = $5
`

type UpdateTaskStatusAndFailureCountParams struct {
	Status       pgtype.Text `json:"status"`
	FailureCount pgtype.Int4 `json:"failure_count"`
	RetryCount   pgtype.Int4 `json:"retry_count"`
	ID           pgtype.UUID `json:"id"`
	UserID       string      `json:"user_id"`
}

func (q *Queries) UpdateTaskStatusAndFailureCount(ctx context.Context, arg UpdateTaskStatusAndFailureCountParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatusAndFailureCount,
		arg.Status,
		arg.FailureCount,
		arg.RetryCount,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateTaskStatusByUserID = `-- name: UpdateTaskStatusByUserID :exec
UPDATE tasks SET status = $1, locked_by = NULL WHERE id = $2 AND user_id = $3
`

type UpdateTaskStatusByUserIDParams struct {
	Status pgtype.Text `json:"status"`
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) UpdateTaskStatusByUserID(ctx context.Context, arg UpdateTaskStatusByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatusByUserID, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateUserAPIKey = `-- name: UpdateUserAPIKey :exec
UPDATE users SET api_key = $1 WHERE id = $2
`

type UpdateUserAPIKeyParams struct {
	ApiKey string `json:"api_key"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateUserAPIKey, arg.ApiKey, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $1 WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role pgtype.Text `json:"role"`
	ID   string      `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserTier = `-- name: UpdateUserTier :exec
UPDATE users SET tier = $1 WHERE id = $2
`

type UpdateUserTierParams struct {
	Tier pgtype.Text `json:"tier"`
	ID   string      `json:"id"`
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) error {
	_, err := q.db.Exec(ctx, updateUserTier, arg.Tier, arg.ID)
	return err
}

const upsertUserSecret = `-- name: UpsertUserSecret :one
INSERT INTO user_secrets (user_id, name, encrypted_value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, name) DO UPDATE SET encrypted_value = $3
RETURNING id
`

type UpsertUserSecretParams struct {
	UserID         string `json:"user_id"`
	Name           string `json:"name"`
	EncryptedValue []byte `json:"encrypted_value"`
}

func (q *Queries) UpsertUserSecret(ctx context.Context, arg UpsertUserSecretParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUserSecret, arg.UserID, arg.Name, arg.EncryptedValue)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertWorkerHeartbeat = `-- name: UpsertWorkerHeartbeat :exec
INSERT INTO worker_heartbeats (worker_id, hostname, last_heartbeat, task_count)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (worker_id) DO UPDATE SET
    last_heartbeat = EXCLUDED.last_heartbeat,
    task_count = EXCLUDED.task_count
`

type UpsertWorkerHeartbeatParams struct {
	WorkerID  string      `json:"worker_id"`
	Hostname  pgtype.Text `json:"hostname"`
	TaskCount pgtype.Int4 `json:"task_count"`
}

func (q *Queries) UpsertWorkerHeartbeat(ctx context.Context, arg UpsertWorkerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertWorkerHeartbeat, arg.WorkerID, arg.Hostname, arg.TaskCount)
	return err
}

const upsertWorkspaceEnvVar = `-- name: UpsertWorkspaceEnvVar :one
INSERT INTO workspace_env_vars (workspace_id, name, value)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, name) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, workspace_id, name, value, created_at, updated_at
`

type UpsertWorkspaceEnvVarParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Value       string      `json:"value"`
}

func (q *Queries) UpsertWorkspaceEnvVar(ctx context.Context, arg UpsertWorkspaceEnvVarParams) (WorkspaceEnvVar, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceEnvVar, arg.WorkspaceID, arg.Name, arg.Value)
	var i WorkspaceEnvVar
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
